#!/bin/bash/

person1="trump"
person2="putin"

echo "$person1:: welcome to alaska"
echo "$person2:: Thank you $person1, finally not on zoom webinar"
echo "$person1:: so. do we have a deal"
echo "$person2:: yes , if you make ukraine joins russia"